config/routes.rb
Rails.application.routes.draw do
  namespace :dashboard do
    resources :recipes
  end
  get :dashboard, to: "dashboard#show"
  devise_for :users

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :main_image
  has_rich_text :instructions
  
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard/recipes_controller.rb
class Dashboard::RecipesController < DashboardController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  def index
    @recipes = current_user.recipes.all.reverse_order
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipes = current_user.recipes.all.reverse_order
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.turbo_stream
        format.html { redirect_to dashboard_recipes_path, notice: 'Recipe was created!' }
        flash.now[:notice] = "Recipe was created."
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @recipes = current_user.recipes.all.reverse_order

    respond_to do |format|
      if @recipe.update(recipe_params)
        format.turbo_stream
        format.html { redirect_to dashboard_recipes_path, notice: 'Recipe was updated' }
        flash.now[:notice] = "Recipe was updated."
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipes = current_user.recipes.all.reverse_order
    @recipe.destroy
    flash.now[:alert] = "Recipe was deleted"
  end

  private
  def set_recipe
    @recipe = current_user.recipes.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :main_image, :instructions)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @recipes = current_user.recipes.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash_stream
    turbo_stream.update "flash", partial: "shared/flash"
  end
end

app/helpers/dashboard/recipes_helper.rb
module Dashboard::RecipesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/_sidebar.html.erb
<%= link_to dashboard_recipes_path, id: 'recipes-link', class: "flex space-x-4 hover:bg-stone-300 group px-4 py-2" do %>
  <svg class="fill-rose-500 group-hover:fill-rose-700 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M416 0C400 0 288 32 288 176V288c0 35.3 28.7 64 64 64h32V480c0 17.7 14.3 32 32 32s32-14.3 32-32V352 240 32c0-17.7-14.3-32-32-32zM64 16C64 7.8 57.9 1 49.7 .1S34.2 4.6 32.4 12.5L2.1 148.8C.7 155.1 0 161.5 0 167.9c0 45.9 35.1 83.6 80 87.7V480c0 17.7 14.3 32 32 32s32-14.3 32-32V255.6c44.9-4.1 80-41.8 80-87.7c0-6.4-.7-12.8-2.1-19.1L191.6 12.5c-1.8-8-9.3-13.3-17.4-12.4S160 7.8 160 16V150.2c0 5.4-4.4 9.8-9.8 9.8c-5.1 0-9.3-3.9-9.8-9L127.9 14.6C127.2 6.3 120.3 0 112 0s-15.2 6.3-15.9 14.6L83.7 151c-.5 5.1-4.7 9-9.8 9c-5.4 0-9.8-4.4-9.8-9.8V16zm48.3 152l-.3 0-.3 0 .3-.7 .3 .7z"/></svg>
  <span class="text-rose-500 group-hover:text-rose-700 font-bold">Recipes</span>
<% end %>

<%= link_to dashboard_recipes_path, id: 'another-link', class: "hidden flex space-x-4 hover:bg-stone-300 group px-4 py-2" do %>
  <svg class="fill-rose-500 group-hover:fill-rose-700 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M96 0C43 0 0 43 0 96V416c0 53 43 96 96 96H384h32c17.7 0 32-14.3 32-32s-14.3-32-32-32V384c17.7 0 32-14.3 32-32V32c0-17.7-14.3-32-32-32H384 96zm0 384H352v64H96c-17.7 0-32-14.3-32-32s14.3-32 32-32zm32-240c0-8.8 7.2-16 16-16H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H144c-8.8 0-16-7.2-16-16zm16 48H336c8.8 0 16 7.2 16 16s-7.2 16-16 16H144c-8.8 0-16-7.2-16-16s7.2-16 16-16z"/></svg>
  <span class="text-rose-500 group-hover:text-rose-700 font-bold">Cookbooks</span>
<% end %>

app/views/dashboard/recipes/_form.html.erb
<%= form_with model: [:dashboard, model], builder: SourdoughFormBuilder, id: 'recipe-form' do |form| %>
  <fieldset class="flex flex-col space-y-2 mb-4">
    <%= form.label "Name of your recipe" %>
    <%= form.text_field :name, placeholder: "i.e. Chocolate Pizza..." %>
  </fieldset>

  <fieldset class="flex flex-col space-y-2 mb-4">
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
  </fieldset>

  <fieldset class="flex flex-col space-y-2 mb-4">
    <%= form.label :instructions %>
    <div class="trix-content-wrapper">
      <%= form.rich_text_area :instructions, placeholder: "Describe the steps for your recipe here", data: { controller: 'trix-toolbar-recipe' } %>
    </div>
  </fieldset>

  <div class="flex items-center space-x-2 mt-4 justify-end">
    <%= form.submit submit %>
    <%= link_to dashboard_recipes_path, class: 'mx-2 text-rose-400 hover:text-rose-700' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    <% end %>
  </div>
<% end %>

app/views/dashboard/recipes/_my_recipes.html.erb
<% object.each do |recipe| %>
  <%= turbo_frame_tag recipe do %>
    <li id="<%= dom_id(recipe) %>" class="recipe-item bg-stone-50 first-of-type:rounded-t-md last-of-type:rounded-b-md px-4 py-2 mb-2 flex justify-between items-center">
      <%= link_to recipe.name, dashboard_recipe_path(recipe), class: "text-cyan-500 font-normal" %>
      <div class="flex items-center justify-end space-x-2">
        <%= link_to edit_dashboard_recipe_path(recipe), id: "update-#{dom_id(recipe)}" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
          </svg>
        <% end %>
        <%= link_to dashboard_recipe_path(recipe), id: "destroy-#{dom_id(recipe)}", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>
      </div>
    </li>
  <% end %>
<% end %>

app/views/dashboard/recipes/create.turbo_stream.erb
<%= turbo_stream.update "recipe-list" do %>
  <% @recipes.each do |recipe| %>
    <li class="bg-stone-50 first-of-type:rounded-t-md last-of-type:rounded-b-md px-4 py-2 mb-2">
      <%= recipe.name %>
    </li>
  <% end %>
<% end %>

app/views/dashboard/recipes/destroy.turbo_stream.erb
<%= turbo_stream.update "recipe-list" do %>
  <%= render partial: 'dashboard/recipes/my_recipes', locals: { object: @recipes } %>
<% end %>

<%= turbo_stream.remove @recipe %>

<%= render_flash_stream %>

app/views/dashboard/recipes/edit.html.erb
<%= turbo_frame_tag dom_id(@recipe) do %>
  <div class="max-w-full bg-stone-50 rounded-md px-4 py-2 mb-2">
    <div class="bg-stone-50">
      <h2><%= t("dashboard.recipes.update_recipe") %> <%= @recipe.name %></h2>
      <%= render partial: 'form', locals: { model: @recipe, submit: "Update" } %>
    </div>
  </div>
<% end %>

app/views/dashboard/recipes/index.html.erb
<div class="grid">
  <div class="mb-8">
    <%= turbo_frame_tag 'new-recipe' do %>
      <h1 class="mb-8"><%= t("dashboard.recipes.your_recipes") %></h1>
      <%= link_to "Add recipe", new_dashboard_recipe_path, class: 'btn btn-submit' %>
    <% end %>
  </div>
  <div>
    <ul id="recipe-list" data-turbo-permanent>
      <div id="my-recipes">
        <%= render partial: 'my_recipes', locals: { object: @recipes } %>
      </div>
    </ul>
  </div>
</div>

app/views/dashboard/recipes/new.html.erb
<%= turbo_frame_tag 'new-recipe' do %>
  <div class="max-w-full bg-stone-50 rounded-md px-4 py-2">
    <div class="bg-stone-50">
      <h2><%= t("dashboard.recipes.write_down_recipe") %></h2>
      <%= render partial: 'form', locals: { model: @recipe, submit: "Add to pantry" } %>
    </div>
  </div>
<% end %>

app/views/dashboard/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<p class="with-side mb-4 text-stone-500">With diced tomatoes, fresh romaine, and black pepper</p>

<% if @recipe.main_image.attached? %>
  <%= image_tag @recipe.main_image, class: "rounded-lg mb-4" %>
<% else %>
  <%= image_tag "food/default.svg", class: "rounded-lg mb-4" %>
<% end %>

<div class="mb-8">
  <h2>Ingredients</h2>
  <ul>
    <li>Romaine lettuce - 20 calories</li>
    <li>Tomatoes - 10 calories</li>
    <li>Black peppper - 5 calories</li>
  </ul>
</div>

<div class="mb-8">
  <h2>Instructions</h2>

  <div>
    <%= @recipe.instructions %>
  </div>
</div>

app/views/dashboard/recipes/update.turbo_stream.erb
<%= turbo_stream.update "recipe-list" do %>
  <%= render partial: 'dashboard/recipes/my_recipes', locals: { object: @recipes } %>
<% end %>

<%= render_flash_stream %>

app/views/dashboard/show.html.erb
<div class="max-w-5xl mx-auto px-4">
  <h1>Welcome to your dashboard!</h1>

  You have <%= link_to "#{current_user.recipes.count} recipes", dashboard_recipes_path %> in your back pocket!
</div>

app/views/home/_user_recipes.html.erb
<div class="grid grid-cols-3 gap-4">
<% current_user.recipes.each do |recipe| %>
  <div id="<%= dom_id(recipe) %>">
    <%= link_to dashboard_recipe_path(recipe) do %>
      <% if recipe.main_image.attached? %>
        <%= image_tag recipe.main_image, class: "rounded-t-lg" %>
      <% else %>
        <%= image_tag "food/salad.jpg", class: "rounded-t-lg" %>
      <% end %>
      <p class="bg-stone-200 w-full px-2 py-2 rounded-b-lg text-center"><%= recipe.name %></p>
    <% end %>
  </div>
<% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= render 'shared/user_welcome' %>
<% else %>
  <div class="max-w-5xl mx-auto px-4 py-8 grid grid-cols-3 gap-4">
    <div class="col-span-3">
      <h1 class="mb-8 md:text-5xl text-cyan-500"><%= t("home_hero") %></h1>
    </div>

    <div class="col-span-2">
      <h2 class="mb-8"><%= t("home_tagline") %></h2>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-submit' %>
    </div>

    <div class="col-span-1">
      <%= image_tag "hero-image.svg" %>
    </div>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pocket Pantry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/nav' %>
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<% content_for :content do %>
    <div class="max-w-5xl mx-auto px-4 py-8 grid grid-cols-5 gap-8">
      <nav class="col-span-1 sidebar">
        <div class="border border-rose-300 rounded-md bg-stone-50">
          <%= render 'dashboard/sidebar' %>
        </div>
      </nav>
      <div class="col-span-4">
        <%= yield %>
      </div>
    </div>
<% end %>

<%= render template: "layouts/application" %>

app/views/shared/_flash.html.erb
<div class="flashes" id="flash">
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash #{type} fixed top-0 left-0 right-0 text-center px-4 py-2 rounded-md bg-rose-100 text-rose-800", data: { controller: "flash" } %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<header>
  <section class="max-w-5xl mx-auto px-4 py-8 flex justify-between items-center">
    <div>
      <%= link_to root_path do %>
        <%= render partial: 'shared/icons/logotype', locals: { text_styles: "fill-rose-600", pocket_styles: "fill-rose-400" } %>
      <% end %>
    </div>

    <div>
      <%= render 'shared/session_portal' %>
    </div>
  </section>
</header>

app/views/shared/_nav_dropdown.html.erb
<div class="flex justify-center">
    <div
        x-data="{
            open: false,
            toggle() {
                if (this.open) {
                    return this.close()
                }

                this.$refs.button.focus()

                this.open = true
            },
            close(focusAfter) {
                if (! this.open) return

                this.open = false

                focusAfter && focusAfter.focus()
            }
        }"
        x-on:keydown.escape.prevent.stop="close($refs.button)"
        x-on:focusin.window="! $refs.panel.contains($event.target) && close()"
        x-id="['dropdown-button']"
        class="relative"
    >
        <!-- Button -->
        <button
            x-ref="button"
            x-on:click="toggle()"
            :aria-expanded="open"
            :aria-controls="$id('dropdown-button')"
            type="button"
            class="flex items-center gap-2 bg-warm-50"
            id="main-nav-menu-button"
        >
            <!-- Heroicon: user-circle -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-rose-500">
              <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>

        </button>

        <!-- Panel -->
        <div
            x-ref="panel"
            x-show="open"
            x-transition.origin.top.left
            x-on:click.outside="close($refs.button)"
            :id="$id('dropdown-button')"
            style="display: none;"
            class="absolute right-0 mt-2 w-40 rounded-md bg-white shadow-md session-dropdown"
        >

            <%= link_to "Dashboard", dashboard_path %>
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, id: "sign-out-link" %>
        </div>
    </div>
</div>

app/views/shared/_session_portal.html.erb
<% if user_signed_in? %>
  <%= render 'shared/nav_dropdown' %>
<% else %>
  <div class="flex space-x-2">
    <%= link_to new_user_session_path, title: "Sign in", id: 'sign-in-link' do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-rose-500">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9" />
      </svg>
    <% end %>
  </div>
<% end %>

app/views/shared/_user_welcome.html.erb
<div class="max-w-5xl mx-auto px-4 py-8">
  <% if current_user.recipes.any? %>
    <h1 class="mb-16 md:text-5xl text-cyan-500">All your favorite recipes, in your back pocket</h1>
    <%= render partial: "home/user_recipes", locals: { recipes: @recipes } %>
  <% else %>
    <div class="px-4 py-2 grid grid-cols-3 gap-8">
      <figure class="col-span-1">
        <%= image_tag "bread-bakers.svg", class: "w-full" %>
      </figure>
      <div class="col-span-2 bg-stone-50 px-4 py-2 h-max">
        <h2 class="mb-8"><%= t("dashboard.recipes.messages.no_recipes") %></h2>

        <%= link_to dashboard_recipes_path, id: "new-recipe-link", class: "flex w-max btn btn-submit space-x-2" do %>
          <svg class="fill-rose-50 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M352 384H64L5.4 178.9C1.8 166.4 0 153.4 0 140.3C0 62.8 62.8 0 140.3 0h3.4c66 0 123.5 44.9 139.5 108.9l31.4 125.8 17.6-20.1C344.8 200.2 362.9 192 382 192h2.8c34.9 0 63.3 28.3 63.3 63.3c0 15.9-6 31.2-16.8 42.9L352 384zM32 448c0-17.7 14.3-32 32-32H352c17.7 0 32 14.3 32 32v32c0 17.7-14.3 32-32 32H64c-17.7 0-32-14.3-32-32V448z"/></svg>
          <span class="text-rose-50">Let's get started</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>